"""Bounded, GUI-neutral Logcat capture foundations."""

from app.modules.logcat.capture_service import (
    CaptureSubscription,
    LogcatCaptureService,
    LogcatServiceResult,
)
from app.modules.logcat.analysis_models import (
    DEFAULT_CONTEXT_AFTER,
    DEFAULT_CONTEXT_BEFORE,
    MAX_CONTEXT_RECORDS,
    MAX_EVENT_SUMMARY,
    MAX_EVENT_TITLE,
    MAX_RELEVANT_RECORDS,
    MAX_STACK_LINE,
    MAX_STACK_LINES,
    MAX_UNIQUE_EVENTS,
    LogcatAnalysisFilter,
    LogcatAnalysisSnapshot,
    LogcatEvent,
    LogcatEventConfidence,
    LogcatEventKind,
    LogcatEventOccurrence,
    LogcatEventSeverity,
)
from app.modules.logcat.analysis_service import LogcatAnalysisService
from app.modules.logcat.detectors import (
    DetectedLogcatEvent,
    LogcatDetectorEngine,
    normalize_fingerprint_text,
    stable_fingerprint,
)
from app.modules.logcat.models import (
    DEFAULT_CAPACITY,
    MAX_CAPACITY,
    MAX_RAW_LINE,
    MIN_CAPACITY,
    LogcatCaptureSnapshot,
    LogcatCaptureState,
    LogcatFilter,
    LogcatPriority,
    LogcatRecord,
)
from app.modules.logcat.parser import ThreadtimeParser

__all__ = (
    "CaptureSubscription",
    "DEFAULT_CONTEXT_AFTER",
    "DEFAULT_CONTEXT_BEFORE",
    "DEFAULT_CAPACITY",
    "DetectedLogcatEvent",
    "LogcatAnalysisFilter",
    "LogcatAnalysisService",
    "LogcatAnalysisSnapshot",
    "LogcatCaptureService",
    "LogcatCaptureSnapshot",
    "LogcatCaptureState",
    "LogcatFilter",
    "LogcatDetectorEngine",
    "LogcatEvent",
    "LogcatEventConfidence",
    "LogcatEventKind",
    "LogcatEventOccurrence",
    "LogcatEventSeverity",
    "LogcatPriority",
    "LogcatRecord",
    "LogcatServiceResult",
    "MAX_CAPACITY",
    "MAX_CONTEXT_RECORDS",
    "MAX_EVENT_SUMMARY",
    "MAX_EVENT_TITLE",
    "MAX_RELEVANT_RECORDS",
    "MAX_RAW_LINE",
    "MAX_STACK_LINE",
    "MAX_STACK_LINES",
    "MAX_UNIQUE_EVENTS",
    "MIN_CAPACITY",
    "ThreadtimeParser",
    "normalize_fingerprint_text",
    "stable_fingerprint",
)
